# Generated by Django 3.2.7 on 2021-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='margin_adj',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=3, verbose_name='margin adjustment'),
        ),
    ]
