# Generated by Django 3.2.7 on 2021-10-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_margin_adj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='SKU'),
        ),
    ]
