# Generated by Django 3.2.7 on 2021-10-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sku',
            new_name='product',
        ),
    ]
