# Generated by Django 3.2.7 on 2021-10-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_sku_inventory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_restocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last restocked at'),
        ),
    ]
