# Generated by Django 3.2.5 on 2021-08-10 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_auto_20210810_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appliancelink',
            options={},
        ),
    ]
