# Generated by Django 3.2.7 on 2021-10-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_auto_20210810_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='configuration'),
        ),
    ]
