# Generated by Django 3.2.7 on 2021-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_alter_appliance_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='consumer_path',
            field=models.CharField(max_length=255, verbose_name='consumer class path'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='appliance name'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('UNRESPONSIVE', 'Unresponsive'), ('NOT_APPLICABLE', 'N/A')], default='DOWN', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='appliancelink',
            constraint=models.UniqueConstraint(fields=('key', 'src'), name='unique_key_by_src'),
        ),
    ]
