# Generated by Django 3.2.5 on 2021-08-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='link key')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst_links', to='appliances.appliance', verbose_name='destination appliance')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='src_links', to='appliances.appliance', verbose_name='source appliance')),
            ],
        ),
    ]
