# Generated by Django 3.2.7 on 2021-11-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BARCODE', 'Barcode'), ('NFC', 'NFC')], max_length=16, verbose_name='kind')),
                ('identifier', models.CharField(max_length=64, verbose_name='identifier')),
                ('object_id', models.CharField(max_length=64, verbose_name='Object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'BOI',
                'verbose_name_plural': 'BOIs',
            },
        ),
    ]
