# Generated by Django 3.2.7 on 2021-11-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boi',
            constraint=models.UniqueConstraint(fields=('identifier', 'kind'), name='unique_identifier_by_kind'),
        ),
    ]
